{% set name = "nambazasimu" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nambazasimu-{{ version }}.tar.gz
  sha256: 76828fc99413cbf00a26aa5c13c105014cd0e9a95414859ff0eed40957bb49fc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - nambazasimu
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/genie360s/nambazasimu
  summary: A package to identify Tanzanian phone number carriers.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - genie360s
